// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJeSXgy7aEKazMfl7mi2eurSf_6fndIg',
    appId: '1:460323191228:android:91c5065db5dd60196bd3b9',
    messagingSenderId: '460323191228',
    projectId: 'flutter-instagram-clone-778d0',
    storageBucket: 'flutter-instagram-clone-778d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5KgMrWS34s3PUOPY6d6DDC8NE6eADt_Q',
    appId: '1:460323191228:ios:0b552fb64425308b6bd3b9',
    messagingSenderId: '460323191228',
    projectId: 'flutter-instagram-clone-778d0',
    storageBucket: 'flutter-instagram-clone-778d0.firebasestorage.app',
    iosClientId: '460323191228-i02cqc90l0sfra4d43vdf2fopnrbaonu.apps.googleusercontent.com',
    iosBundleId: 'com.lukascoding.flutterInstagramClone.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5KgMrWS34s3PUOPY6d6DDC8NE6eADt_Q',
    appId: '1:460323191228:ios:0b552fb64425308b6bd3b9',
    messagingSenderId: '460323191228',
    projectId: 'flutter-instagram-clone-778d0',
    storageBucket: 'flutter-instagram-clone-778d0.firebasestorage.app',
    iosClientId: '460323191228-i02cqc90l0sfra4d43vdf2fopnrbaonu.apps.googleusercontent.com',
    iosBundleId: 'com.lukascoding.flutterInstagramClone.stg',
  );
}
