// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVC9P_gZyiyuAV8opsJdAxN7N88nOGvYw',
    appId: '1:980912473842:android:630db70e29af8e8381726b',
    messagingSenderId: '980912473842',
    projectId: 'flutter-instagram-clone-b4064',
    storageBucket: 'flutter-instagram-clone-b4064.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBIcL_KRc1TJzOj6gl5kL1OMfqwsbxUco',
    appId: '1:980912473842:ios:725916db268b499e81726b',
    messagingSenderId: '980912473842',
    projectId: 'flutter-instagram-clone-b4064',
    storageBucket: 'flutter-instagram-clone-b4064.firebasestorage.app',
    iosClientId: '980912473842-rhu2trobfeqsakmksfflsbfrbb5f2ns9.apps.googleusercontent.com',
    iosBundleId: 'com.lukascoding.flutterInstagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBIcL_KRc1TJzOj6gl5kL1OMfqwsbxUco',
    appId: '1:980912473842:ios:725916db268b499e81726b',
    messagingSenderId: '980912473842',
    projectId: 'flutter-instagram-clone-b4064',
    storageBucket: 'flutter-instagram-clone-b4064.firebasestorage.app',
    iosClientId: '980912473842-rhu2trobfeqsakmksfflsbfrbb5f2ns9.apps.googleusercontent.com',
    iosBundleId: 'com.lukascoding.flutterInstagramClone',
  );
}
