// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUBWYuPpo2lxM7cPgrYkRI7bww6WArHII',
    appId: '1:659247163733:android:5aefd1688c2cb5401be7dc',
    messagingSenderId: '659247163733',
    projectId: 'flutter-instagram-clone-75c5e',
    storageBucket: 'flutter-instagram-clone-75c5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD42O5cyZZLN731yvOLiggs5jwgoMRHTTc',
    appId: '1:659247163733:ios:12abcd51e3c67f831be7dc',
    messagingSenderId: '659247163733',
    projectId: 'flutter-instagram-clone-75c5e',
    storageBucket: 'flutter-instagram-clone-75c5e.firebasestorage.app',
    iosClientId: '659247163733-2m1r0j836g0hfo4l6h4pc6jtq24elv5s.apps.googleusercontent.com',
    iosBundleId: 'com.lukascoding.flutterInstagramClone.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD42O5cyZZLN731yvOLiggs5jwgoMRHTTc',
    appId: '1:659247163733:ios:12abcd51e3c67f831be7dc',
    messagingSenderId: '659247163733',
    projectId: 'flutter-instagram-clone-75c5e',
    storageBucket: 'flutter-instagram-clone-75c5e.firebasestorage.app',
    iosClientId: '659247163733-2m1r0j836g0hfo4l6h4pc6jtq24elv5s.apps.googleusercontent.com',
    iosBundleId: 'com.lukascoding.flutterInstagramClone.dev',
  );
}
